spring:
    datasource:
        name: test
        url: jdbc:mysql://47.94.205.153:3306/qdu?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
        username: root
        password: QDU.freestyle.top000
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations:   classpath:mapper/*.xml
  type-aliases-package: qdu.graduation.backend.entity

